title: Sharavan's Homepage
description: Questions and Answers to simple simple yet recurring issues
author: Sharavan Koushik
github: https://github.com/Lrisingr
about: What i Love. Python , Manga , DoTa 2 , Math , Games with noShit.
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/Profile.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/sharavankoushik"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/sharavan-koushik/"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/lrisingr"

share:
  twitter_username: sharavankoushik

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://lrisingr.github.io"
baseurl: ""
paginate: 20
per_page: 20
highlighter: rouge
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
